# This Action's primary task is build & publish Docker Image on registry.

name: CI

# Trigger Settings for our service.
on:
  # Triggers the Job only iff pull request is created corresponding to the main branch,
  # Or if there is any added commits on our Silo.
  pull_request:
    branches: [ main ]
  push:
    branches: [ Silo ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Base Image for our Job.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
